#ej_11 productos
#funcion del program
def preciof(cant,precio):
	result=(cant*precio)
	return(result)
#progra
d1=input("ingrese el producto: ")
d1_2=int(input("ingrese la cantidad que quiere comprar: "))
d1_3=int(input("ingrese el precio: "))
print("-"*10)
d2=input("ingrese el producto: ")
d2_2=int(input("ingrese la cantidad que quiere comprar: "))
d2_3=int(input("ingrese el precio: "))
print("-"*10)
d3=input("ingrese el producto: ")
d3_2=int(input("ingrese la cantidad que quiere comprar: "))
d3_3=int(input("ingrese el precio: "))
print("-"*10)
d4=input("ingrese el producto: ")
d4_2=int(input("ingrese la cantidad que quiere comprar: "))
d4_3=int(input("ingrese el precio: "))
x=preciof(d1_2,d1_3)
y=preciof(d2_2,d2_3)
z=preciof(d3_2,d3_3)
h=preciof(d4_2,d4_3)
preccomplet=x+y+z+h
print("-"*10)
print("producto: ", d1,"\ncantidad: ",d1_2,"\nprecio",d1_3,"\nprecio final: ",x)
print("-"*10)
print("producto: ", d2,"\ncantidad: ",d2_2,"\nprecio",d2_3,"\nprecio final: ",y)
print("-"*10)
print("producto: ", d3,"\ncantidad: ",d3_2,"\nprecio",d3_3,"\nprecio final: ",z)
print("-"*10)
print("producto: ", d4,"\ncantidad: ",d4_2,"\nprecio",d4_3,"\nprecio final: ",h)
print("-"*10)
print("el total a pagar es: ", preccomplet)
